# Set base URL for site - should end with a trailing slash
baseUrl = "https://blog.funwith.app/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Fun with Flutter"
theme = "hermit"


# Will appear below the footer links with a © sign and the current year
# TODO
# copyright = "Fun with Flutter — All rights reserved."

pygmentsCodeFences = true               # Enable highlighting inside codefences
pygmentsCodeFencesGuessSyntax = true    # Highlight code without language tag
# pygmentsUseClasses = true               # Use external style sheet
# pygmentsUseClassic = true              # Force use of chroma
pygmentsStyle = "dracula"

# pygmentsCodefences = true               # Enable highlighting inside codefences
# pygmentsCodeFencesGuessSyntax = true    # Highlight code without language tag
# pygmentsUseClasses = true               # Use external style sheet
# pygmentsUseClassic = false              # Force use of chroma

#todo
# canonifyURLs = true
# preserveTaxonomyNames = true

#todo
# Configure pagination
# paginate = 10
# paginatePath = "page"


[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  # description = ""
  # images = [""]
  themeColor = "#494f5c"

  homeSubtitle = "Blog for the Fun with Flutter YouTube channel"
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  # bgImg = ""  # Homepage background-image URL

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = "https://github.com/username/repository/commit/"

  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent = false  # Set "text-align: justify" to `.content`.

  relatedPosts = false  # Add a related content section to all single posts page

  code_copy_button = true # Turn on/off the code-copy-button for code-fields
  
#   Add custom css
#   customCSS = ["css/syntax.css"]

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.
  [[params.social]]
    name = "youtube"
    url = "https://www.youtube.com/funwithflutter"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/FunFlutter"

  [[params.social]]
    name = "github"
    url = "https://github.com/funwithflutter/"

# [menu]

#   [[menu.main]]
#     name = "Posts"
#     url = "posts/"
#     weight = 10

#   [[menu.main]]
#     name = "About"
#     url = "about-hugo/"
#     weight = 20

#todo
# [params]
#     # Site subtitle (not shown if commented out or set to false)
#     subtitle = "Blog"

#     # Site description
#     description = "Companion Blog for the Fun with Flutter YouTube channel"

#     # Favicon file (relative to baseURL - place below static folder)
#     favicon = "favicon.png"
#     # Custom css file (relative to baseURL - place below static folder)
#     css = "custom.css"

#     # Define formatting of dates
#     # (optional, falls back to RFC822 format if not set)
#     # For reference to date and time formatting, see:
#     # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
#     # Make sure to set showMetaDates to true to see any dates
#     dateFmt = "Mon, 02 Jan 2006 15:04:05 MST"

#     # Customize the text of the 404 page here
#     errorPageText = "There's nothing to see here, please move along!"

#     # Header with title/subtitle can be disabled here.
#     # (If you disable this, add some link on the index page inside menu.main,
#     #  otherwise your visitors will get confused and lost...)
#     showNavHeader = true

#     # Decide if only summaries are shown on the main page or the full content
#     showFullContent = true

#     # If false no pagination is shown when there is nothing to paginate
#     showEmptyPagination = true

#     # If false the dates for the posts are not shown
#     showMetaDates = true

#     # If false the taxonomy links for the posts are not shown
#     showMetaLinks = true

#     # Uses Hugo internal templates if set
#     opengraph = false
#     schema = false
#     twitter_cards = false


# Define all supported taxonomies (add series to the default)
[taxonomies]
    tag = "tags"
    thumbnail = "thumbnails"
    description = "descriptions"
    # categories = "categories"
    # series = "series"

# disableKinds = ["RSS"]


[author]
    name = "Gordon Hayes"
    email = "funwithflutter@gmail.com"


[menu]

    # Configure main menu entries (header)
    # Currently set to list all taxonomies and posts
    [[menu.main]]
        identifier = "post"
        name = "Posts"
        title = "All posts"
        url = "/posts/"
        weight = 10

    #[[menu.main]]
    #    identifier = "categories"
    #    name = "Categories"
    #    title = "All categories"
    #    url = "/categories/"
    #    weight = 2

    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        title = "All tags"
        url = "/tags/"
        weight = 20

    [[menu.main]]
        name = "About"
        url = "about-hugo/"
        weight = 30

    #[[menu.main]]
    #    identifier = "series"
    #    name = "Series"
    #    title = "All series"
    #    url = "/series/"
    #    weight = 2


    # Define the entries for post metadata
    # Identifiers should match with the taxonomy entries
    #[[menu.meta]]
    #    identifier = "categories"
    #    name = "Categories"
    #    weight = 1
    #[[menu.meta]]
    #    identifier = "series"
    #    name = "Series"
    #    weight = 2
    # [[menu.meta]]
    #     identifier = "tags"
    #     name = "Tags"
    #     weight = 3


    # Add some footer links to your likings
    [[menu.footer]]
        name = "GitHub"
        title = "Fun with Github repository"
        url = "https://github.com/funwithflutter/"
        weight = 1

    [[menu.footer]]
        name = "YouTube"
        title = "Fun with Flutter YouTube"
        url = "https://www.youtube.com/funwithflutter"
        weight = 2

[outputs]
  home = ["json","html", "RSS"]
  page = ["html","RSS"]
  section = ["html"]